// Run with: npx electron scripts/studio-smoke.cjs
// Real renderer components with a delayed, in-memory IPC fixture; never opens user data.
const { app, BrowserWindow } = require('electron')
const { mkdtempSync, writeFileSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { join, resolve } = require('node:path')
const assert = require('node:assert/strict')
const output = mkdtempSync(join(tmpdir(), 'bikorch-studio-smoke-'))
console.log('Studio smoke artifacts: ' + output)
app.setPath('userData', join(output, 'electron-data'))
app.commandLine.appendSwitch('disable-gpu')
let server
let win
const delay = (ms) => new Promise((done) => setTimeout(done, ms))
const evaluate = async (source) => {
  try {
    return await win.webContents.executeJavaScript(source)
  } catch (error) {
    throw new Error(`Renderer evaluation failed for ${source}: ${error}`, { cause: error })
  }
}
async function until(source, label) {
  const deadline = Date.now() + 30_000
  let lastError
  while (Date.now() < deadline) {
    try {
      if (await evaluate(source)) return
    } catch (error) {
      // A navigation can replace the execution context between polling attempts.
      lastError = error
    }
    await delay(80)
  }
  throw new Error('Timed out: ' + label + (lastError ? ` (${lastError})` : ''))
}
async function screenshot(name, width, height) {
  win.setContentSize(width, height)
  await delay(180)
  await until(`[...document.querySelectorAll('.workspace-sidebar-overlay, .animate-scale-in')].every(element => getComputedStyle(element).opacity === '1')`, 'surface animations settled')
  const overflow = await evaluate(`(() => {
    const selectors = ['.welcome-screen', '.welcome-action-card', '.welcome-recent-row', '.studio-launcher', '.app-header', '.workspace-frame'];
    return selectors.flatMap(selector => [...document.querySelectorAll(selector)].filter(el => el.getBoundingClientRect().width > 0 && (el.getBoundingClientRect().right > innerWidth + 1 || el.scrollWidth > el.clientWidth + 2)).map(() => selector));
  })()`)
  writeFileSync(join(output, name + '.png'), (await win.webContents.capturePage()).toPNG())
  assert.deepEqual(overflow, [], name + ' has horizontal overflow')
}

app.whenReady().then(async () => {
  const { createServer } = await import('vite')
  const react = (await import('@vitejs/plugin-react')).default
  const tailwind = (await import('@tailwindcss/vite')).default
  server = await createServer({
    configFile: false,
    root: resolve(__dirname, '..'),
    plugins: [react(), tailwind()],
    resolve: { alias: { '@renderer': resolve(__dirname, '../src/renderer'), '@shared': resolve(__dirname, '../src/shared') } },
    server: { host: '127.0.0.1', port: 0 },
    logLevel: 'error'
  })
  await server.listen()
  win = new BrowserWindow({ show: false, width: 1280, height: 900, webPreferences: { contextIsolation: true, nodeIntegration: false, backgroundThrottling: false } })
  const errors = []
  win.webContents.on('console-message', (_event, level, message) => { if (level === 3) errors.push(message) })
  await win.loadURL(server.resolvedUrls.local[0] + 'scripts/fixtures/studio-preview.html')
  await until(`Boolean(document.querySelector('.welcome-action-card'))`, 'welcome')
  await screenshot('home-desktop', 1280, 900)
  await screenshot('home-tablet', 768, 1024)
  await screenshot('home-mobile', 390, 844)
  await screenshot('home-small', 360, 740)
  // Picker cancellation must leave the original welcome screen usable.
  await evaluate(`window.studioFixture.setFolder(null); document.querySelector('.welcome-action-card').click()`)
  await delay(180)
  assert.equal(await evaluate(`Boolean(document.querySelector('.welcome-action-card'))`), true, 'cancel picker')
  await evaluate(`window.studioFixture.setFolder('/projects/aurora-studio'); document.querySelector('.welcome-action-card').click()`)
  await until(`Boolean(document.querySelector('.studio-launcher'))`, 'open project')
  await until(`getComputedStyle(document.querySelector('.studio-launcher-content')).opacity === '1'`, 'workspace launcher visible')
  assert.equal(await evaluate(`document.querySelector('.studio-launch-intro h1').textContent`), 'Work with your agents')
  assert.equal(await evaluate(`document.querySelectorAll('.studio-launch-row').length`), 6, 'direct agent and terminal launchers')
  assert.equal(await evaluate(`document.querySelector('.studio-manager-launch strong').textContent`), 'Manager', 'optional Manager entry')
  await screenshot('workspace-mobile', 390, 844)
  await screenshot('workspace-desktop', 1280, 900)
  await until(`document.querySelector('[data-cli-kind="cursor"] .studio-launch-role').textContent === 'Not installed'`, 'CLI detection')
  assert.equal(await evaluate(`document.querySelector('[data-cli-kind="cursor"] .studio-launch-row').disabled`), true, 'missing CLI is disabled')
  assert.equal(await evaluate(`document.querySelector('[data-cli-kind="claude"] .studio-launch-row').disabled`), false, 'installed CLI is enabled')
  await evaluate(`window.studioFixture.setInstallFailure(true); document.querySelector('[aria-label="Install Cursor CLI"]').click()`)
  await until(`Boolean(document.querySelector('[aria-label="Installing Cursor CLI"]'))`, 'install busy state')
  assert.equal(await evaluate(`document.querySelector('[data-cli-kind="cursor"] .studio-launch-row').disabled`), true, 'install does not activate early')
  await until(`document.querySelector('.studio-cli-errors')?.textContent.includes('Fixture download failed')`, 'failed installation')
  assert.equal(await evaluate(`window.studioFixture.accounts().length`), 0, 'failed install creates no account')
  await evaluate(`window.studioFixture.setInstallFailure(false); document.querySelector('[aria-label="Install Cursor CLI"]').click()`)
  await until(`document.querySelector('[data-cli-kind="cursor"] .studio-launch-row').disabled === false`, 'successful installation')
  assert.equal(await evaluate(`Boolean(document.querySelector('[aria-label="Install Cursor CLI"]'))`), false, 'download icon disappears after installation')
  await evaluate(`document.querySelector('[data-cli-kind="cursor"] .studio-launch-row').click()`)
  await until(`window.studioFixture.panels().some(panel => panel.type === 'cursor' && panel.launchMode === 'login' && panel.accountId)`, 'installed CLI opens account sign-in')
  assert.equal(await evaluate(`window.studioFixture.accounts().length`), 1, 'sign-in creates a managed account')
  await evaluate(`document.querySelector('[aria-label="Show CLI accounts"]').click()`)
  await until(`Boolean(document.querySelector('[aria-label="Add CLI"]'))`, 'account panel')
  await evaluate(`document.querySelector('[aria-label="Add CLI"]').click()`)
  await until(`Boolean(document.querySelector('.cli-kind-picker-sheet [data-cli-kind="gemini"] .cli-install-button'))`, 'account picker download')
  await screenshot('accounts-install-mobile', 390, 844)
  await evaluate(`document.querySelector('.cli-kind-picker-sheet [aria-label="Install Gemini CLI"]').click()`)
  await until(`document.querySelector('.cli-kind-picker-sheet [data-cli-kind="gemini"] .cli-kind-tile').disabled === false`, 'account picker activates after install')
  await screenshot('accounts-install-desktop', 1280, 900)
  await evaluate(`document.querySelector('.cli-kind-picker-sheet [data-cli-kind="gemini"] .cli-kind-tile').click()`)
  await until(`window.studioFixture.panels().some(panel => panel.type === 'gemini' && panel.launchMode === 'login' && panel.accountId)`, 'account picker opens sign-in')
  assert.deepEqual(await evaluate(`window.studioFixture.cliInstalls`), ['cursor', 'cursor', 'gemini'], 'only clicked CLIs are installed, including retry')
  await evaluate(`document.querySelector('[aria-label="Hide sidebar"]').click()`)
  await evaluate(`document.querySelector('button[aria-label="Add panel"]').click()`)
  await until(`Boolean(document.querySelector('[role="menu"][aria-label="Add panel"]'))`, 'panel menu')
  assert.equal(await evaluate(`document.querySelector('.panel-menu-cli-option[data-cli-kind="antigravity"] .menu-action').disabled`), true, 'panel menu disables missing CLI')
  await screenshot('panel-menu-cli-install', 1280, 900)
  await evaluate(`document.querySelector('.panel-menu-cli-option [aria-label="Install Antigravity CLI"]').click()`)
  await until(`document.querySelector('.panel-menu-cli-option[data-cli-kind="antigravity"] .menu-action').disabled === false`, 'panel menu installation')
  await evaluate(`const button = document.querySelector('.panel-menu-cli-option[data-cli-kind="antigravity"] .menu-action'); button.click(); button.click()`)
  await until(`!document.querySelector('[role="menu"][aria-label="Add panel"]')`, 'panel menu launches sign-in')
  assert.equal(await evaluate(`window.studioFixture.accounts().filter(account => account.kind === 'antigravity').length`), 1, 'double click creates one account')
  await evaluate(`document.querySelector('[aria-label="Tools"]').click()`)
  assert.equal(await evaluate(`document.querySelector('[aria-label="Tools"]').getAttribute('aria-expanded')`), 'true', 'tools expand separately')
  await evaluate(`document.querySelector('[aria-label="Tools"]').click()`)
  await evaluate(`document.querySelector('[aria-label="Show files"]').click()`)
  await until(`document.querySelector('.file-tree-list')?.textContent.includes('README.md')`, 'registered project files')
  assert.deepEqual(await evaluate('window.studioFixture.errors'), [])
  await evaluate(`document.querySelector('.file-tree-row.is-folder').click()`)
  await until(`document.querySelector('.file-tree-branch')?.textContent.includes('Empty folder')`, 'empty subfolder')
  const count = await evaluate(`window.studioFixture.reads['/projects/aurora-studio/empty']`)
  await delay(450)
  assert.equal(await evaluate(`window.studioFixture.reads['/projects/aurora-studio/empty']`), count, 'empty folder must not repeatedly load')
  await evaluate(`window.studioFixture.setFailure(true); document.querySelector('.file-tree-row.is-folder').click()`)
  await until(`document.querySelector('.file-tree-row.is-folder').getAttribute('aria-expanded') === 'false'`, 'collapse folder')
  await evaluate(`new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))`)
  await evaluate(`document.querySelector('.file-tree-row.is-folder').click()`)
  await until(`Boolean(document.querySelector('.file-tree-inline-error'))`, 'subfolder error')
  const failedCount = await evaluate(`window.studioFixture.reads['/projects/aurora-studio/empty']`)
  await delay(450)
  assert.equal(await evaluate(`window.studioFixture.reads['/projects/aurora-studio/empty']`), failedCount, 'failed subfolder must not automatically retry')
  await evaluate(`window.studioFixture.setFailure(false); document.querySelector('.file-tree-inline-error button').click()`)
  await until(`document.querySelector('.file-tree-branch')?.textContent.includes('Empty folder')`, 'subfolder retry')
  await screenshot('files-desktop', 1280, 900)
  await evaluate(`window.studioFixture.setFailure(true); document.querySelector('[aria-label="Refresh files"]').click()`)
  await until(`Boolean(document.querySelector('.file-tree-error'))`, 'folder recovery UI')
  assert.equal(await evaluate(`document.querySelector('.file-tree-error').textContent.includes('Error invoking')`), false)
  await screenshot('files-recovery-mobile', 390, 844)
  await evaluate(`window.studioFixture.setFailure(false); document.querySelector('.file-tree-error button').click()`)
  await until(`document.querySelector('.file-tree-list')?.textContent.includes('README.md')`, 'retry recovers')
  await evaluate(`window.studioFixture.setFailure(true); document.querySelector('[aria-label="Refresh files"]').click()`)
  await until(`Boolean(document.querySelector('.file-tree-error'))`, 'reconnect error')
  await evaluate(`window.studioFixture.setFailure(false); window.studioFixture.setFolder('/projects/relocated'); document.querySelectorAll('.file-tree-error button')[1].click()`)
  await until(`document.querySelector('.file-tree-meta')?.textContent.includes('relocated') && document.querySelector('.file-tree-list')?.textContent.includes('README.md')`, 'reconnect moved root')
  assert.equal(await evaluate(`document.querySelectorAll('[role="tab"]').length`), 1, 'reconnect must update the same project, not add a duplicate')
  await evaluate(`window.studioFixture.switchProject('slow-project')`)
  await until(`Boolean(window.studioFixture.reads['/projects/slow-project'])`, 'slow request started')
  await evaluate(`window.studioFixture.switchProject('new-project')`)
  await until(`document.querySelector('.file-tree-meta')?.textContent.includes('new-project') && document.querySelector('.file-tree-list')?.textContent.includes('README.md')`, 'switch project')
  await delay(800)
  assert.equal(await evaluate(`document.querySelector('.file-tree-list').textContent.includes('old-project.txt')`), false, 'stale reads must not overwrite the active project')
  await evaluate(`document.querySelector('[aria-label="Project home"]').click()`)
  await until(`document.querySelectorAll('.welcome-recent-row').length === 3`, 'home with projects')
  await screenshot('home-projects-desktop', 1280, 900)
  await screenshot('home-projects-mobile', 390, 844)
  await evaluate(`document.querySelector('.welcome-recent-row').click()`)
  await until(`Boolean(document.querySelector('.studio-launcher'))`, 'reopen saved project')
  await win.loadURL(server.resolvedUrls.local[0] + 'scripts/fixtures/studio-preview.html?bootstrap=1')
  await until(`Boolean(document.querySelector('[data-bootstrap-ready]'))`, 'StrictMode bootstrap')
  await delay(1000)
  assert.equal(await evaluate(`document.querySelector('[data-bootstrap-ready]').dataset.bootstrapError`), '')
  assert.equal(await evaluate('window.studioFixture.emptySaves()'), 0, 'effect replay must not persist the empty pre-hydration store')
  assert.equal(await evaluate(`document.querySelector('.project-tab-name').textContent`), 'Restored project')
  await win.loadURL(server.resolvedUrls.local[0] + 'scripts/fixtures/cli-login-preview.html')
  await until(`window.loginFixture?.panel()?.loginStarted === true`, 'terminal login started')
  assert.equal(await evaluate(`window.loginFixture.panel().launchMode`), 'login', 'login mode persists before authentication')
  await evaluate(`window.loginFixture.end()`)
  await until(`[...document.querySelectorAll('button')].some(button => button.textContent === 'Retry')`, 'stopped login retry')
  await evaluate(`[...document.querySelectorAll('button')].find(button => button.textContent === 'Retry').click()`)
  await until(`window.loginFixture.creates.at(-1)?.resumeLogin === true`, 'pending login resumes')
  await evaluate(`window.loginFixture.setReady(true)`)
  await until(`window.loginFixture.accounts()[0]?.profileReady === true`, 'login captured without terminal output')
  assert.equal(await evaluate(`window.loginFixture.panel().launchMode`), undefined, 'login marker clears after authentication')
  await evaluate(`window.loginFixture.remount()`)
  await until(`window.loginFixture.creates.at(-1)?.launchMode === 'normal'`, 'live terminal reattached after sign-in')
  assert.equal(await evaluate(`window.loginFixture.worktrees()`), 0, 'reattachment preserves the live login terminal folder')
  await evaluate(`window.loginFixture.end()`)
  await until(`[...document.querySelectorAll('button')].some(button => button.textContent === 'Retry')`, 'authenticated terminal retry')
  await evaluate(`[...document.querySelectorAll('button')].find(button => button.textContent === 'Retry').click()`)
  await until(`window.loginFixture.worktrees() > 0 && window.loginFixture.creates.at(-1)?.worktreePath`, 'new authenticated session uses worktree')
  await evaluate(`window.loginFixture.setReady(false); window.loginFixture.end()`)
  await until(`[...document.querySelectorAll('button')].some(button => button.textContent === 'Retry')`, 'expired terminal retry')
  await evaluate(`[...document.querySelectorAll('button')].find(button => button.textContent === 'Retry').click()`)
  await until(`[...document.querySelectorAll('button')].some(button => button.textContent === 'Sign in')`, 'expired account recovery action')
  await evaluate(`[...document.querySelectorAll('button')].find(button => button.textContent === 'Sign in').click()`)
  await until(`window.loginFixture.panel()?.loginStarted === true && window.loginFixture.creates.at(-1)?.launchMode === 'login'`, 'expired account signs in again')
  await evaluate(`window.loginFixture.setReady(true); window.loginFixture.remount()`)
  await until(`window.loginFixture.accounts()[0]?.profileReady === true && window.loginFixture.creates.at(-1)?.launchMode === 'normal'`, 'saved credentials recovered before restarting login')
  assert.equal(await evaluate(`window.loginFixture.accounts().length`), 1, 'recovery retains one account')
  await screenshot('terminal-login-recovery', 1280, 900)
  assert.deepEqual(errors, [], 'renderer console errors')
  console.log('Studio smoke passed: 4 viewport sizes, CLI setup, account sign-in, terminal retry/resume, output-independent authentication, live terminal reattachment, expired account recovery, folder recovery, project home and StrictMode bootstrap.')
  console.log('Screenshots: ' + output)
  win.destroy()
  await server.close()
  app.exit(0)
}).catch(async (error) => {
  console.error(error)
  if (win && !win.isDestroyed()) win.destroy()
  if (server) await server.close()
  app.exit(1)
})
